

drop table person if exists;

create table person (
  id int generated by default as identity not null,
  first_name varchar(64) not null,
  last_name varchar(64) not null,
  for_paging_test boolean not null,
  primary key (id)
);
